import assert from 'node:assert/strict';
import {createAdminStore,decide,validateCampaign,isPublished,unresolved,syncCatalog} from './admin-model';
import {balance,withdraw,initialState,makeProject,deliveryComplete} from './data';
const admin=createAdminStore();
const applied=admin.samples.projects[0];
assert.throws(()=>decide(admin.samples,applied.id,'rejected',''),/填写/);
const accepted=decide(admin.samples,applied.id,'confirm','期待你的城市影像');
assert.equal(accepted.projects[0].stage,'confirm');
assert.equal(accepted.projects[0].messages.at(-1)?.text,'期待你的城市影像');
assert.throws(()=>decide(accepted,applied.id,'confirm',''),/不允许/);
const review=admin.samples.projects[1];
assert.throws(()=>decide(admin.samples,review.id,'revision',''),/填写/);
assert.equal(decide(admin.samples,review.id,'revision','请补充实拍体验').projects[1].feedback,'请补充实拍体验');
assert.ok(unresolved(review,{},review.id));
assert.equal(unresolved(review,{[review.id]:review.messages.length},review.id),false);
const newMessage={...review,messages:[...review.messages,{who:'我',text:'补充一个问题'}]};
assert.ok(unresolved(newMessage,{[review.id]:review.messages.length},review.id));
const awaiting=admin.samples.projects[2];
assert.throws(()=>decide(admin.samples,awaiting.id,'publish',''),/填写/);
assert.equal(decide(admin.samples,awaiting.id,'publish','请使用单条作品链接').projects[2].returnReason,'请使用单条作品链接');
const settled=decide(decide(admin.samples,awaiting.id,'settlement','验收通过'),awaiting.id,'paid','已结算');
assert.ok(balance(settled)>balance(admin.samples));
assert.throws(()=>decide(settled,awaiting.id,'paid',''),/不允许/);
const campaign={...admin.catalog[0],id:'test-campaign',deadline:'2099-12-31',listing:'draft' as const};
assert.equal(validateCampaign(campaign,true),'');
assert.ok(validateCampaign({...campaign,budget:0},true));
assert.ok(validateCampaign({...campaign,deadline:'2000-01-01'},true));
assert.equal(isPublished(campaign),false);
assert.equal(isPublished({...campaign,listing:'published'}),true);
syncCatalog([...admin.catalog,campaign]);
const custom={...makeProject(campaign.id),items:Object.fromEntries(campaign.deliverable.split(' + ').map(x=>[x,'内容']))};
assert.ok(deliveryComplete(custom));
const real=initialState();real.projects=[makeProject(campaign.id)];
assert.equal(decide(real,real.projects[0].id,'confirm','').projects[0].stage,'confirm');
assert.equal(admin.samples.projects[0].stage,'applied');
console.log('PASS: administrator approval guards, revision reasons, message resolution/reopen, settlement idempotency, campaign validation and custom campaign integration.');
