export type Campaign={id:string;brand:string;title:string;subtitle:string;region:string;platform:string;category:string;budget:number;deadline:string;days:number;deliverable:string;image?:string;color:string;mark:string;match:number;verified:boolean;tags:string[];brief:string;requirements:string[]};
export const images={dji:'https://www1.djicdn.com/cms/uploads/d4617084bfd8eb39f1c8bbbfc737213a%40770%2A462.jpg',insta:'https://res.insta360.com/static/656a69138bf1263c182be638c7826c37/EN.jpg?x-oss-process=image%2Fauto-orient%2C1%2Fquality%2Cq_85',anker:'https://cdn.shopify.com/s/files/1/0489/1980/6120/files/f190c947-4f1e-4cae-a9a0-ef44c1debf1f.__CR0_0_1200_900_PT0_SX600_V1.jpg?v=1690785704'};
export const campaigns:Campaign[]=[
{id:'dji-air',brand:'DJI',title:'从天空，重新发现中东',subtitle:'DJI Air 3 · 中东影像创作者计划',region:'中东',platform:'YouTube',category:'影像',budget:1800,deadline:'2026-10-15',days:22,deliverable:'1 条 3–5 分钟视频 + 3 张照片',image:images.dji,color:'#353f4d',mark:'DJI',match:98,verified:true,tags:['航拍影像','旅行','科技'],brief:'让观众跟随你的镜头，看见中东的另一种可能。从迪拜的城市线条到沙漠日落，用 DJI Air 3 记录一次有故事的旅行。',requirements:['以真实体验为主线，展示城市与自然两种拍摄场景','视频中包含至少 30 秒航拍素材及产品使用体验','以中文或英文创作，注明品牌合作关系','遵循拍摄地要求，自行确认飞行许可与可拍摄区域']},
{id:'dji-pocket',brand:'DJI',title:'把城市日常，拍成电影',subtitle:'Osmo Pocket 3 · 城市漫游日记',region:'全球',platform:'Instagram',category:'旅行',budget:750,deadline:'2026-10-18',days:25,deliverable:'1 条 60 秒竖屏视频',color:'#25354c',mark:'DJI',match:96,verified:false,tags:['城市漫游','生活方式'],brief:'用一段城市漫游，把日常变成值得收藏的电影片段。分享你使用 Osmo Pocket 3 记录生活的真实体验。',requirements:['60 秒竖屏视频，包含 3 个不同场景','自然展示拍摄体验，不照读参数','标注品牌合作关系']},
{id:'insta-outdoor',brand:'Insta360',title:'去户外，换个视角',subtitle:'Ace Pro 2 · 周末探索计划',region:'全球',platform:'Instagram',category:'户外',budget:1200,deadline:'2026-10-20',days:27,deliverable:'1 条户外短视频 + 1 条 Story',image:images.insta,color:'#1a8ed1',mark:'Insta360',match:94,verified:true,tags:['户外运动','创意影像'],brief:'骑行、露营或沿海公路，记录一个真正属于自己的周末。从出发到归来，用一个新的视角讲述你的户外故事。',requirements:['展示至少两种户外拍摄场景','包含实际使用感受与原始拍摄片段','竖屏 60–90 秒，附一条幕后 Story']},
{id:'anker-travel',brand:'Anker',title:'带着灵感，轻装出发',subtitle:'Anker Prime · 移动创作装备',region:'全球',platform:'YouTube',category:'科技',budget:800,deadline:'2026-10-22',days:29,deliverable:'1 条装备体验视频',image:images.anker,color:'#91c3d3',mark:'Anker',match:92,verified:false,tags:['数码装备','旅行'],brief:'一次旅途，也是一次移动工作。分享你的随身创作装备，展示充电与移动办公的实际体验。',requirements:['展示真实差旅使用场景','清晰说明体验条件，不夸大性能','3 分钟以上视频，注明合作关系']},
{id:'notion-work',brand:'Notion',title:'给创意，一个生长的空间',subtitle:'创作者工作流 · 灵感整理计划',region:'全球',platform:'X',category:'效率',budget:450,deadline:'2026-10-12',days:19,deliverable:'1 组图文 + 1 份模板展示',color:'#edece8',mark:'N',match:89,verified:false,tags:['创作效率','工作流'],brief:'把选题、拍摄计划和灵感整理成你的创作工作流，用真实案例分享如何更轻松地开始一项创作。',requirements:['图文展示完整工作流','模板使用虚构信息，不包含个人隐私','提供可理解的使用步骤']},
{id:'allbirds-walk',brand:'allbirds',title:'慢下来，走进新的风景',subtitle:'城市步行 · 周末微旅行',region:'中国',platform:'Instagram',category:'生活方式',budget:500,deadline:'2026-10-25',days:32,deliverable:'1 组生活方式图文',color:'#dfe6da',mark:'allbirds',match:86,verified:false,tags:['生活方式','城市旅行'],brief:'在熟悉的城市里发现新的路线，用镜头记录一段不赶时间的周末步行，分享自己的真实穿着感受。',requirements:['6 张以上原创照片与路线记录','呈现真实穿着体验','明确标注品牌合作关系']}
];
export type Stage='applied'|'confirm'|'draft'|'review'|'revision'|'publish'|'acceptance'|'settlement'|'paid'|'rejected'|'withdrawn'|'declined'|'negotiating';
export type Project={id:string;campaignId:string;stage:Stage;draft:string;fileName:string;version:number;link:string;note:string;history:string[];submittedAt:string;acceptedAt?:string;paidAt?:string;returnReason?:string;feedback?:string;termsVersion:number;termsNote:string;confirmedTerms?:number;items:Record<string,string>;versions:{number:number;draft:string;fileName:string;items?:Record<string,string>;at?:string}[];messages:{who:string;text:string}[]};
export type Account={method:string;name:string;address:string;region:string};
export type Withdrawal={id:string;amount:number;account:Account;createdAt:string;status:'processing'|'completed'|'failed'};
export type Profile={name:string;email:string;region:string;language:string;topic:string;social:string};
export type AppState={profile:Profile;verified:boolean;socialVerified:boolean;verifiedEmail:string;certifications:Record<string,string>;applicationDrafts:Record<string,string>;messageDrafts:Record<string,string>;readNotifications:string[];projects:Project[];withdrawals:Withdrawal[];accounts:Account[]};
export const stageInfo:Record<Stage,{label:string;task:string;next:string;color:string}>={
applied:{label:'等待品牌确认',task:'品牌正在查看你的报名',next:'预计 2 个工作日内反馈。你可以继续发现其他活动。',color:'amber'},
confirm:{label:'待确认合作',task:'确认这一次合作',next:'先确认报酬、交付要求与时间，确认后再开始创作。',color:'blue'},
draft:{label:'待提交初稿',task:'让创意，成为作品',next:'请在 10 月 28 日前提交初稿，品牌将在 2 个工作日内反馈。',color:'blue'},
review:{label:'品牌审核中',task:'初稿已收到，等待反馈',next:'审核通过后才需要发布，请先保留当前版本。',color:'amber'},
revision:{label:'需要修改',task:'根据反馈，完善作品',next:'品牌已留下 2 条反馈。请更新内容并提交新版本。',color:'orange'},
publish:{label:'待发布内容',task:'你的作品已通过审核',next:'按约定的平台与时间发布已通过的版本，并回填公开链接。',color:'blue'},
acceptance:{label:'等待验收',task:'链接已提交，等待验收',next:'品牌正在核对发布内容。请保持链接公开可访问。',color:'amber'},
settlement:{label:'待结算',task:'合作已验收，报酬即将到账',next:'预计验收后 7 个工作日内到账，待结算款项暂不可提现。',color:'amber'},
paid:{label:'已完成',task:'这一次合作，圆满完成',next:'报酬已进入钱包。下一次值得期待的合作，正在路上。',color:'green'},
negotiating:{label:'协商中',task:'等待新版合作约定',next:'品牌更新约定后，请重新核对并决定是否接受。',color:'amber'},
withdrawn:{label:'已撤回',task:'报名已撤回',next:'未进入合作，不会产生交付任务。',color:'gray'},
declined:{label:'已拒绝合作',task:'合作邀请已拒绝',next:'没有接受合作约定，不会产生交付任务。',color:'gray'},
rejected:{label:'未入选',task:'这次没能一起合作',next:'不是每次匹配都刚刚好，继续发现适合你的品牌。',color:'gray'}
};
export const needsAction=(s:Stage)=>['confirm','draft','revision','publish'].includes(s);
export function makeProject(id:string,stage:Stage='applied'):Project{return {id:'p-'+id,campaignId:id,stage,draft:'',fileName:'',version:0,link:'',note:'',submittedAt:new Date().toISOString(),termsVersion:1,termsNote:'按活动详情所列交付清单与时间执行。',items:{},history:[new Date().toLocaleString('zh-CN')+' · '+(stage==='applied'?'报名已提交':'演示订单已创建')],versions:[],messages:[{who:'项目负责人 · Mia',text:'你好，欢迎参与这次品牌合作。有任何问题，都可以在这里留言。'}]};}
export function initialState(demo=false):AppState{const dji=makeProject('dji-air','confirm'),insta=makeProject('insta-outdoor','revision'),anker=makeProject('anker-travel','paid');insta.draft='用骑行与海岸露营，记录一个真实的周末。';insta.version=1;insta.fileName='周末探索_初稿.mp4';insta.versions=[{number:1,draft:insta.draft,fileName:insta.fileName}];const profile={name:'When2buy',email:'creator@example.com',region:'中国',language:'中文',topic:'影像 / 科技 / 旅行',social:'https://x.com/your_account'};anker.acceptedAt=new Date().toISOString();anker.paidAt=new Date().toISOString();insta.items=Object.fromEntries(deliverables('insta-outdoor').map(k=>[k,'示例内容：'+k]));insta.feedback='V1 · Mia：请在户外视频中补充实际使用体验，Story 中补充拍摄场景。';return {profile:demo?profile:{name:'',email:'',region:'中国',language:'中文',topic:'',social:''},verified:demo,verifiedEmail:demo?profile.email:'',socialVerified:false,certifications:{},applicationDrafts:{},messageDrafts:{},readNotifications:[],projects:demo?[dji,insta,anker]:[],withdrawals:[],accounts:[]};}
export const transitions:Record<Stage,Stage[]>={applied:['confirm','rejected','withdrawn'],confirm:['draft','declined','negotiating'],negotiating:['confirm','declined'],withdrawn:[],declined:[],draft:['review'],review:['revision','publish'],revision:['review'],publish:['acceptance'],acceptance:['publish','settlement'],settlement:['paid'],paid:[],rejected:[]};
export function advance(state:AppState,id:string,next:Stage):AppState{const p=state.projects.find(p=>p.id===id);if(!p||!transitions[p.stage].includes(next))throw Error('当前状态不允许此操作');return {...state,projects:state.projects.map(p=>p.id===id?{...p,stage:next,...(next==='settlement'?{acceptedAt:new Date().toISOString()}:{}),...(next==='paid'?{paidAt:new Date().toISOString()}:{}),history:[...p.history,new Date().toLocaleString('zh-CN')+' · '+stageInfo[next].label]}:p)};}
export function balance(state:AppState){return state.projects.filter(p=>p.stage==='paid').reduce((n,p)=>n+(campaigns.find(c=>c.id===p.campaignId)?.budget||0),0)-state.withdrawals.filter(w=>w.status!=='failed').reduce((n,w)=>n+w.amount,0);}
export function withdraw(state:AppState,amount:number,account:Account):AppState{if(!Number.isFinite(amount)||amount<50||Math.abs(amount*100-Math.round(amount*100))>0.000001||amount>balance(state)||!state.accounts.some(a=>a.address===account.address&&a.method===account.method))throw Error('请检查金额、余额与收款账户');return {...state,withdrawals:[{id:'WD-'+(state.withdrawals.length+1).toString().padStart(4,'0'),amount,account:{...account},createdAt:new Date().toISOString(),status:'processing'},...state.withdrawals]};}

export const closedStages:Stage[]=['rejected','withdrawn','declined'];
export function normalizeAccount(url:string){try{const u=new URL(url);return u.hostname.toLowerCase().replace(/^www\./,'')+u.pathname.replace(/\/$/,'').toLowerCase()}catch{return ''}}
export function socialPlatform(url:string){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol)||!u.pathname.replace(/\//g,''))return '';const h=u.hostname.toLowerCase().replace(/^www\./,'');return h==='youtube.com'||h==='youtu.be'?'YouTube':h==='instagram.com'?'Instagram':h==='x.com'||h==='twitter.com'?'X':''}catch{return ''}}
export function certified(s:AppState,platform:string){return !!s.certifications[platform]&&s.certifications[platform]===normalizeAccount(s.profile.social)&&socialPlatform(s.profile.social)===platform}
export function updateProfile(s:AppState,profile:Profile):AppState{return {...s,profile,verified:s.verifiedEmail.toLowerCase()===profile.email.trim().toLowerCase(),certifications:normalizeAccount(profile.social)===normalizeAccount(s.profile.social)?s.certifications:{},socialVerified:false}}
export function recommendation(c:Campaign,p:Profile){const reasons:string[]=[];if([c.category,...c.tags].some(t=>p.topic.toLowerCase().includes(t.toLowerCase())))reasons.push('方向匹配');if(socialPlatform(p.social)===c.platform)reasons.push('发布平台匹配');if(c.region==='全球'||c.region===p.region||(c.region==='中东'&&['阿联酋','沙特阿拉伯'].includes(p.region)))reasons.push('地区适用');return reasons}
export function daysLeft(c:Campaign){return Math.max(0,Math.ceil((new Date(c.deadline+'T23:59:59+08:00').getTime()-Date.now())/86400000))}
export function deliverables(id:string){return campaigns.find(c=>c.id===id)!.deliverable.split(' + ')}
export function deliveryComplete(p:Project){return deliverables(p.campaignId).every(k=>!!p.items[k]?.trim())}
export function notificationId(p:Project){return p.id+':'+p.history.length+':'+p.stage}
export function expectedPayment(iso?:string){if(!iso)return '验收后生成具体日期';const d=new Date(iso);let n=0;while(n<7){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)n++}return d.toLocaleDateString('zh-CN')}
export function moneyError(value:string,available:number){const n=Number(value);if(!value.trim())return '请输入提现金额';if(!Number.isFinite(n))return '请输入有效金额';if(n<50)return '最低提现金额为 USD 50';if(n>available)return '金额超过可提现余额';if(Math.abs(n*100-Math.round(n*100))>0.000001)return '金额最多保留两位小数';return ''}
export function saveAccount(s:AppState,a:Account,index:number|null):AppState{if(s.accounts.some((v,i)=>i!==index&&v.method===a.method&&v.address.trim().toLowerCase()===a.address.trim().toLowerCase()))throw Error('该收款账户已存在，请选择已有账户');return {...s,accounts:index===null?[...s.accounts,{...a}]:s.accounts.map((v,i)=>i===index?{...a}:v)}}

export function campaignDate(c:Campaign,offset:number){const d=new Date(c.deadline+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)}
export function nextTaskDate(p:Project){const c=campaigns.find(c=>c.id===p.campaignId)!;return campaignDate(c,['publish','acceptance'].includes(p.stage)?14:7)}
